### PR TITLE
display phone# label in search results refs #210 

### PR DESCRIPTION
**Pull request by robertoschwald**
Adds support to display the localized phone# label to search results in #210

### CODE REVIEW

**Comment by robertoschwald** [comment]
Example:

telephone_label_example

**Comment by madhavajay** [comment]
Looks great, lets get this merged!!

**Comment by robertoschwald** [comment]
Whats the problem this PR isn't merged since May?
Do you need more info or any code changes?

**Comment by eofster** [comment]
Sorry for the delay. I had also considered this way of solving this problem at some point in the past, but decided not to do that, because it leaks some information – the type of the number – to the other party.

After the text is entered into the field it is parsed and a SIP URI is constructed. When the format is `Text <phone>`, the `Text` part becomes the `Display Name` part of the URI. From the screenshot above, the other party will be able to see “Example User - Mobil” as the callee’s name. But imagine if somebody had “Example User - Shitty Phone” there or similar.

I know, it doesn’t seem like something very serious for the majority of users, but it does leak the info that is not expected to be leaked. It’s not other’s business which labels one uses for the phones in her personal address book.

This problem should be solved by the new in-app contact search UI.

**Comment by robertoschwald** [comment]
I'll keep a private fork of master with this PR applied until you release the new in-app contact search-UI in the future on https://github.com/robertoschwald/Telephone/tree/label_support as we badly need this feature.

**Comment by RandallKent** [comment]
@eofster - Who do you mean by "the other party"? I was under the impression that the Telephone.app pulls entries from Contacts.app?

**Pull request closed without merging**
